/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

export default {
  operators: {
    client: [
      '_actions',
      '_and',
      '_api',
      '_args',
      '_array',
      '_base64',
      '_date',
      '_divide',
      '_eq',
      '_event',
      '_event_log',
      '_function',
      '_get',
      '_global',
      '_gt',
      '_gte',
      '_if',
      '_if_none',
      '_index',
      '_input',
      '_intl',
      '_js',
      '_json',
      '_location',
      '_log',
      '_lt',
      '_lte',
      '_math',
      '_media',
      '_menu',
      '_ne',
      '_not',
      '_number',
      '_object',
      '_operator',
      '_or',
      '_product',
      '_random',
      '_regex',
      '_request',
      '_request_details',
      '_state',
      '_string',
      '_subtract',
      '_sum',
      '_switch',
      '_theme',
      '_type',
      '_uri',
      '_url_query',
      '_user',
    ],
    server: [
      '_and',
      '_args',
      '_array',
      '_base64',
      '_date',
      '_divide',
      '_eq',
      '_function',
      '_get',
      '_gt',
      '_gte',
      '_hash',
      '_if',
      '_if_none',
      '_intl',
      '_item',
      '_js',
      '_json',
      '_log',
      '_lt',
      '_lte',
      '_math',
      '_ne',
      '_not',
      '_number',
      '_object',
      '_operator',
      '_or',
      '_payload',
      '_product',
      '_random',
      '_regex',
      '_secret',
      '_state',
      '_step',
      '_string',
      '_subtract',
      '_sum',
      '_switch',
      '_type',
      '_uri',
      '_user',
    ],
  },
};
