/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import tagStyle from './format/tagStyle.js';
import TONE_COLORS from './format/toneColors.js';

function toDeclarations(style) {
  return Object.entries(style)
    .map(([property, value]) => {
      const cssProperty = property.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`);
      return `    ${cssProperty}: ${value};`;
    })
    .join('\n');
}

// Scoped to HTML that HtmlComponent enhanced (its root carries data-lf-html),
// and wrapped in :where() so the rules have no specificity: app styles,
// Tailwind utilities and inline styles all win.
function scoped(selector) {
  return `:where([data-lf-html] ${selector})`;
}

function toneRules() {
  return Object.entries(TONE_COLORS)
    .map(
      ([tone, color]) =>
        `  ${scoped(`[data-tag="${tone}"]`)},\n  ${scoped(
          `[data-status="${tone}"]`
        )} {\n    --lf-tone: ${color};\n  }`
    )
    .join('\n');
}

// The stylesheet for HTML attributes, written to dist/html.css at package
// build time and imported by the app's globals.css. The tag look and the tone
// table come from the same functions the ag-grid tag cells use.
function createHtmlCss() {
  return `/* Generated by @lowdefy/block-utils (src/createHtmlCss.js). Do not edit. */
@layer components {
  ${scoped('[data-tag]')} {
    --lf-tone: ${TONE_COLORS.default};
${toDeclarations(tagStyle('var(--lf-tone)'))}
  }
  ${scoped('[data-status]')} {
    --lf-tone: ${TONE_COLORS.default};
    display: inline-flex;
    align-items: center;
    gap: var(--ant-margin-xs, 8px);
  }
  ${scoped('[data-status]')}::before {
    content: '';
    flex: none;
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background: var(--lf-tone);
  }
${toneRules()}
  ${scoped('[data-popover-content]')} {
    display: none;
  }
  ${scoped('[data-format]')} {
    font-variant-numeric: tabular-nums;
  }
  ${scoped('[data-avatar]')} {
    --lf-avatar-color: var(--ant-color-info);
    display: inline-flex;
    flex: none;
    align-items: center;
    justify-content: center;
    box-sizing: border-box;
    width: var(--lf-avatar-size, var(--ant-control-height-sm, 24px));
    min-width: var(--lf-avatar-size, var(--ant-control-height-sm, 24px));
    height: var(--lf-avatar-size, var(--ant-control-height-sm, 24px));
    overflow: hidden;
    border-radius: 50%;
    vertical-align: middle;
    font-size: var(--lf-avatar-font-size, var(--ant-font-size-sm, 12px));
    line-height: 1;
    white-space: nowrap;
    user-select: none;
    color: var(--ant-color-text-light-solid, #fff);
    background: var(--lf-avatar-color);
  }
  ${scoped('img[data-avatar]')} {
    object-fit: cover;
    background: transparent;
  }
  ${scoped('[data-avatar][data-avatar-shape="square"]')} {
    border-radius: var(--ant-border-radius, 6px);
  }
  ${scoped('[data-avatar][hidden]')} {
    display: none;
  }
  ${scoped('[data-lf-copy]')} {
    display: inline-flex;
    vertical-align: middle;
    margin-inline-start: var(--ant-margin-xxs, 4px);
  }
  ${scoped('[data-lf-copy] > button')} {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    margin: 0;
    padding: 2px;
    border: 0;
    border-radius: var(--ant-border-radius-sm, 4px);
    background: transparent;
    color: var(--ant-color-text-tertiary);
    font: inherit;
    line-height: 1;
    cursor: pointer;
  }
  ${scoped('[data-lf-copy] > button:hover')} {
    color: var(--ant-color-text);
    background: var(--ant-color-fill-tertiary);
  }
  ${scoped('[data-lf-copy] > button:focus-visible')} {
    outline: var(--ant-line-width-focus, 2px) solid var(--ant-color-primary-border);
    outline-offset: 1px;
  }
  ${scoped('[data-lf-visually-hidden]')} {
    position: absolute;
    width: 1px;
    height: 1px;
    margin: -1px;
    padding: 0;
    overflow: hidden;
    clip-path: inset(50%);
    white-space: nowrap;
    border: 0;
  }
  ${scoped('[data-status="processing"]')}::before {
    animation: lf-status-processing 1.2s ease-in-out infinite;
  }
  @media (prefers-reduced-motion: reduce) {
    ${scoped('[data-status="processing"]')}::before {
      animation: none;
    }
  }
  @keyframes lf-status-processing {
    50% {
      opacity: 0.35;
    }
  }
}
`;
}

export default createHtmlCss;
