/*
  Copyright 2020 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import React from 'react';
import { create, act } from 'react-test-renderer';
import ErrorBoundary from './ErrorBoundary';

test('no error', () => {
  let comp;
  act(() => {
    comp = create(
      <ErrorBoundary>
        <div>one</div>
      </ErrorBoundary>
    );
  });
  act(() => {
    comp.update(
      <ErrorBoundary>
        <div>one</div>
      </ErrorBoundary>
    );
  });
  expect(comp.toJSON()).toMatchInlineSnapshot(`
    <div>
      one
    </div>
  `);
});

test('display no error message on error generated by child', () => {
  console.error = () => undefined;
  const ProblemChild = () => {
    throw new Error('ErrorBoundary test error');
  };
  let comp;
  act(() => {
    comp = create(
      <ErrorBoundary>
        <ProblemChild />
      </ErrorBoundary>
    );
  });

  act(() => {
    comp.update(
      <ErrorBoundary>
        <ProblemChild />
      </ErrorBoundary>
    );
  });
  expect(comp.toJSON()).toMatchInlineSnapshot(`""`);
});

test('display error message on error generated by child', () => {
  console.error = () => undefined;
  const ProblemChild = () => {
    throw new Error('ErrorBoundary test error');
  };
  let comp;
  act(() => {
    comp = create(
      <ErrorBoundary renderError>
        <ProblemChild />
      </ErrorBoundary>
    );
  });

  act(() => {
    comp.update(
      <ErrorBoundary renderError>
        <ProblemChild />
      </ErrorBoundary>
    );
  });
  expect(comp.toJSON()).toMatchInlineSnapshot(`
    <div>
      Error: ErrorBoundary test error
    </div>
  `);
});

test('display error message and description on error generated by child', () => {
  console.error = () => undefined;
  const ProblemChild = () => {
    throw new Error('ErrorBoundary test error');
  };
  let comp;
  act(() => {
    comp = create(
      <ErrorBoundary renderError description="error description">
        <ProblemChild />
      </ErrorBoundary>
    );
  });

  act(() => {
    comp.update(
      <ErrorBoundary renderError description="error description">
        <ProblemChild />
      </ErrorBoundary>
    );
  });
  expect(comp.toJSON()).toMatchInlineSnapshot(`
    <div>
      Error: ErrorBoundary test error
      <br />
      error description
    </div>
  `);
});

test('display fallback component on error generated by child', () => {
  console.error = () => undefined;
  const ProblemChild = () => {
    throw new Error('ErrorBoundary test error');
  };
  let comp;
  act(() => {
    comp = create(
      <ErrorBoundary fallback={(error) => <div>fallback: {error.message}</div>}>
        <ProblemChild />
      </ErrorBoundary>
    );
  });

  act(() => {
    comp.update(
      <ErrorBoundary fallback={(error) => <div>fallback: {error.message}</div>}>
        <ProblemChild />
      </ErrorBoundary>
    );
  });
  expect(comp.toJSON()).toMatchInlineSnapshot(`
    <div>
      fallback: 
      ErrorBoundary test error
    </div>
  `);
});
