/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import path from 'path';

import YAML from 'yaml';
import { writeFile } from '@lowdefy/node-utils';

import moduleLockfileName from './moduleLockfileName.js';

const generatedComment =
  '# This file is generated by the Lowdefy build. Commit it.\n' +
  '# It pins each GitHub module entry to the commit the build fetched.\n';

async function writeModuleLockfile({ configDirectory, lockfile }) {
  const ids = Object.keys(lockfile).sort();
  const ordered = {};
  for (const id of ids) {
    const { source, ref, commit, fetchedAt } = lockfile[id];
    ordered[id] = { source, ref, commit, fetchedAt };
  }

  const content =
    ids.length === 0 ? generatedComment : `${generatedComment}${YAML.stringify(ordered)}`;
  await writeFile(path.join(configDirectory, moduleLockfileName), content);
}

export default writeModuleLockfile;
