/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import path from 'node:path';

import YAML from 'yaml';
import { writeFileIfChanged } from '@lowdefy/node-utils';

import moduleLockfileName from './moduleLockfileName.js';

// A byte-for-byte mirror of packages/build/src/build/writeModuleLockfile.js,
// which owns the lockfile format. The CLI cannot import it yet (@lowdefy/build
// is not a CLI dependency); writeFileIfChanged so an update that changes
// nothing does not touch the file's mtime.
const generatedComment =
  '# This file is generated by the Lowdefy build. Commit it.\n' +
  '# It pins each GitHub module entry to the commit the build fetched.\n';

async function writeModuleLockfile({ configDirectory, lockfile }) {
  const filePath = path.join(configDirectory, moduleLockfileName);
  const sortedIds = Object.keys(lockfile).sort();
  const ordered = {};
  for (const id of sortedIds) {
    const { source, ref, commit } = lockfile[id];
    ordered[id] = { source, ref, commit };
  }

  const content =
    sortedIds.length === 0 ? generatedComment : `${generatedComment}${YAML.stringify(ordered)}`;

  return writeFileIfChanged(filePath, content);
}

export default writeModuleLockfile;
