/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import fs from 'fs';
import path from 'path';
import { buildPageJit } from '@lowdefy/build/dev';

import createLogger from './log/createLogger.js';
import getDevState from './devState.js';
import PageCache from './pageCache.mjs';

const jitLogger = createLogger({ name: 'jit-build' });

function formatDuration(ms) {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
}

// Pages built since the last invalidation. The lowdefy() Vite plugin runs in
// the same process and invalidates through the shared dev state — the
// previous mtime checks on invalidatePages/pageRegistry.json are gone.
const pageCache = new PageCache();

// Page builds are serialized: they mutate the shared build context (errors,
// key namespace, file caches) which is single-threaded by design. Warm
// builds take milliseconds, so queueing concurrent first visits is cheap.
let buildQueue = Promise.resolve();

function enqueueBuild(run) {
  const result = buildQueue.then(run);
  buildQueue = result.catch(() => {});
  return result;
}

async function buildPageIfNeeded({ pageId }) {
  const state = getDevState();
  if (state.pageCache !== pageCache) {
    state.pageCache = pageCache;
  }

  // The live registry from shallowBuild is a Map (the previous file restore
  // produced a plain object).
  const registry = state.pageRegistry;
  const pageEntry = typeof registry?.get === 'function' ? registry.get(pageId) : registry?.[pageId];
  if (!pageEntry) {
    return false;
  }

  if (pageCache.isCompiled(pageId)) {
    return true;
  }

  const shouldBuild = await pageCache.acquireBuildLock(pageId);
  if (!shouldBuild) {
    // Another request completed the build
    return true;
  }

  try {
    return await enqueueBuild(() => buildPageNow({ pageId, registry, state }));
  } finally {
    pageCache.releaseBuildLock(pageId);
  }
}

async function buildPageNow({ pageId, registry, state }) {
  // Invalidation may have landed while queued — rebuilding anyway is correct,
  // just possibly redundant.
  jitLogger.info({ spin: 'start' }, `Building page "${pageId}"...`);
  const startTime = Date.now();
  // The live shallow-build context — refMap, keyMap, jsMap, typesMap, and
  // modules continue in memory. No artifact restore: producer and consumer
  // share the process.
  const result = await buildPageJit({
    pageId,
    pageRegistry: registry,
    context: state.buildContext,
  });
  if (result && result.installing) {
    jitLogger.info(
      `Installing plugin packages for page "${pageId}": ${result.packages.join(', ')}. ` +
        'The page will be available once they are installed.'
    );
    return result;
  }
  pageCache.markCompiled(pageId);
  // Touch the candidates file so Vite's CSS pipeline re-runs Tailwind for
  // classes the JIT build discovered — globals.css imports it. This import
  // is the ONLY recompile trigger: the tailwind .html scan inputs are
  // excluded from Vite's watcher (their .html change events would force
  // full browser reloads). Only touched when the build actually changed
  // tailwind content, so unchanged rebuilds cause no CSS recompile.
  if (result?._tailwindChanged) {
    fs.writeFileSync(
      path.join(state.buildContext.directories.build, 'tailwind-candidates.css'),
      `/* Generated by Lowdefy build — rewritten on page changes to trigger CSS recompilation */\n/* ${Date.now()} */\n`
    );
  }
  jitLogger.info(
    { spin: 'succeed', color: 'white' },
    `Built page "${pageId}" in ${formatDuration(Date.now() - startTime)}.`
  );
  return { built: true, warnings: result?._warnings };
}

export default buildPageIfNeeded;
