/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import fs from 'fs';
import path from 'path';

import { type } from '@lowdefy/helpers';

function pascalCase(id) {
  return id
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function createShimContent({ notification, typeDefinition, appEmail }) {
  const componentName = `${pascalCase(notification.notificationId)}Preview`;
  // Shallow merge, matching the runtime theme resolution.
  const theme = { ...appEmail, ...(notification.theme ?? {}) };
  // The preview has no serverUrl — match the runtime fallback for relative
  // logos (drop it, EmailLayout shows the companyName text header) instead of
  // rendering a broken image.
  if (type.isString(theme.logo) && theme.logo.startsWith('/') && !theme.logo.startsWith('//')) {
    delete theme.logo;
  }
  const config = {
    id: notification.notificationId,
    type: notification.type,
    properties: notification.properties ?? {},
    theme,
    testData: notification.testData ?? {},
  };
  // React.createElement instead of JSX syntax so the shim is immune to the
  // preview toolchain's JSX runtime configuration.
  return `// Generated by lowdefy emails. Do not edit.
import React from 'react';
import { ${typeDefinition.originalTypeName} as Template } from '${
    typeDefinition.package
  }/notifications';
import { buildPreviewProps } from '@lowdefy/email-templates';

const config = ${JSON.stringify(config, null, 2)};

function ${componentName}(props) {
  return React.createElement(Template, props);
}
// A wrapper component per shim — setting PreviewProps on the shared imported
// template would clobber across notifications using the same template type.
${componentName}.PreviewProps = buildPreviewProps({ Template, config });

export default ${componentName};
`;
}

async function generateEmailShims({ context, notifications, appEmail, notificationTypes }) {
  const emailsDirectory = context.directories.emails;
  const serverDirectory = context.directories.server;

  await fs.promises.rm(emailsDirectory, { recursive: true, force: true });
  await fs.promises.mkdir(emailsDirectory, { recursive: true });

  // Bare imports in the shims resolve against the server's installed tree.
  // 'junction' works unprivileged on Windows; on POSIX it creates a normal
  // directory symlink.
  await fs.promises.symlink(
    path.join(serverDirectory, 'node_modules'),
    path.join(emailsDirectory, 'node_modules'),
    'junction'
  );

  for (const notification of notifications) {
    const typeDefinition = notificationTypes[notification.type];
    if (!typeDefinition) {
      context.logger.warn(
        `Notification "${notification.notificationId}": template type "${notification.type}" not found in the build types map. Skipping preview.`
      );
      continue;
    }
    const content = createShimContent({ notification, typeDefinition, appEmail });
    await fs.promises.writeFile(
      path.join(emailsDirectory, `${notification.notificationId}.jsx`),
      content
    );
  }
}

export default generateEmailShims;
