/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import fs from 'fs';
import path from 'path';
import YAML from 'yaml';

function collectClassValue(value, classes) {
  if (typeof value === 'string') {
    value.split(/\s+/).forEach((c) => {
      if (c) classes.add(c);
    });
  } else if (Array.isArray(value)) {
    for (const item of value) {
      if (typeof item === 'string') classes.add(item);
    }
  } else if (value && typeof value === 'object') {
    for (const v of Object.values(value)) {
      collectClassValue(v, classes);
    }
  }
}

function extractClasses(obj, classes) {
  if (!obj || typeof obj !== 'object') return;
  if (Array.isArray(obj)) {
    for (const item of obj) extractClasses(item, classes);
    return;
  }
  for (const [key, value] of Object.entries(obj)) {
    if (key === 'class') {
      collectClassValue(value, classes);
    } else {
      extractClasses(value, classes);
    }
  }
}

async function updatePageTailwindCss({ changedFiles, context }) {
  const newClasses = new Set();
  changedFiles
    .filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'))
    .forEach((f) => {
      try {
        const content = fs.readFileSync(
          path.join(context.directories.config, f),
          'utf8'
        );
        const doc = YAML.parse(content);
        extractClasses(doc, newClasses);
      } catch {
        // YAML parse error — skip
      }
    });

  if (newClasses.size === 0) return;

  const tailwindClassesPath = path.join(
    context.directories.build,
    'tailwind-classes.js'
  );
  let existingClasses = new Set();
  try {
    const existing = fs.readFileSync(tailwindClassesPath, 'utf8');
    const match = existing.match(/export default "(.*)"/);
    if (match) {
      existingClasses = new Set(match[1].split(' ').filter(Boolean));
    }
  } catch {
    // File doesn't exist yet
  }

  let cssNeeded = false;
  for (const cls of newClasses) {
    if (!existingClasses.has(cls)) {
      existingClasses.add(cls);
      cssNeeded = true;
    }
  }

  if (cssNeeded) {
    const classesJs = `// Generated by Lowdefy build — Tailwind scans this for class candidates\nexport default "${[...existingClasses].join(' ')}";\n`;
    fs.writeFileSync(tailwindClassesPath, classesJs);
    await context.compileCss();
  }
}

export default updatePageTailwindCss;
