/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import readModuleLockfile from './readModuleLockfile.js';
import writeModuleLockfile from './writeModuleLockfile.js';

function makeConfigDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'lowdefy-lock-'));
}

const entryA = {
  source: 'github:acme/modules/a@main',
  ref: 'main',
  commit: '4f0a1c9b2e7d5a3f8c1b6e0d9a4f7c2b5e8d1a30',
};
const entryB = {
  source: 'github:acme/modules/b@v2.1.0',
  ref: 'v2.1.0',
  commit: '9c3e5b1f7a2d4e8c0b6f3a9d5e1c7b4a2f6d0e83',
};

test('writeModuleLockfile writes the generated comment and entries in stable key order', async () => {
  const configDirectory = makeConfigDir();
  await writeModuleLockfile({ configDirectory, lockfile: { zebra: entryB, alpha: entryA } });

  const content = fs.readFileSync(path.join(configDirectory, 'lowdefy-modules.lock.yaml'), 'utf8');
  expect(content).toMatchInlineSnapshot(`
"# This file is generated by the Lowdefy build. Commit it.
# It pins each GitHub module entry to the commit the build fetched.
alpha:
  source: github:acme/modules/a@main
  ref: main
  commit: 4f0a1c9b2e7d5a3f8c1b6e0d9a4f7c2b5e8d1a30
zebra:
  source: github:acme/modules/b@v2.1.0
  ref: v2.1.0
  commit: 9c3e5b1f7a2d4e8c0b6f3a9d5e1c7b4a2f6d0e83
"
`);
  fs.rmSync(configDirectory, { recursive: true });
});

test('writeModuleLockfile output round trips through readModuleLockfile', async () => {
  const configDirectory = makeConfigDir();
  await writeModuleLockfile({ configDirectory, lockfile: { alpha: entryA, zebra: entryB } });
  await expect(readModuleLockfile({ configDirectory })).resolves.toEqual({
    alpha: entryA,
    zebra: entryB,
  });
  fs.rmSync(configDirectory, { recursive: true });
});

test('writeModuleLockfile writes only the comment for an empty lockfile', async () => {
  const configDirectory = makeConfigDir();
  await writeModuleLockfile({ configDirectory, lockfile: {} });
  const content = fs.readFileSync(path.join(configDirectory, 'lowdefy-modules.lock.yaml'), 'utf8');
  expect(content).toBe(
    '# This file is generated by the Lowdefy build. Commit it.\n' +
      '# It pins each GitHub module entry to the commit the build fetched.\n'
  );
  fs.rmSync(configDirectory, { recursive: true });
});

test('writeModuleLockfile does not rewrite an unchanged lockfile', async () => {
  const configDirectory = makeConfigDir();
  expect(await writeModuleLockfile({ configDirectory, lockfile: { alpha: entryA } })).toBe(true);
  expect(await writeModuleLockfile({ configDirectory, lockfile: { alpha: entryA } })).toBe(false);
  fs.rmSync(configDirectory, { recursive: true });
});

test('writeModuleLockfile ignores fields that are not part of a lock entry', async () => {
  // fetchedAt was dropped from the entry shape: it pinned nothing and made the
  // shared lockfile churn on every re-resolve.
  const configDirectory = makeConfigDir();
  await writeModuleLockfile({
    configDirectory,
    lockfile: { alpha: { ...entryA, extra: 'ignored', fetchedAt: '2026-08-30T09:14:22.183Z' } },
  });
  await expect(readModuleLockfile({ configDirectory })).resolves.toEqual({ alpha: entryA });
  fs.rmSync(configDirectory, { recursive: true });
});
