/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import fs from 'fs';
import path from 'path';
import { cleanDirectory, copyFileOrDirectory, writeFile } from '@lowdefy/node-utils';

import copyTracedFiles from '../../utils/copyTracedFiles.js';
import findTraceBase from '../../utils/findTraceBase.js';

// The boot script chdirs into the server directory inside the output (it is nested when the app
// is a pnpm workspace member) so the server's cwd-relative reads of build/ and dist/client work,
// then imports the entrypoint. .mjs so it runs as ESM regardless of a package.json at its root.
function startScript({ relServer }) {
  const relServerPosix = relServer === '' ? '.' : relServer.split(path.sep).join('/');
  return `// Generated by \`lowdefy docker-output\` — boots the server from the traced output.
import path from 'node:path';
import url from 'node:url';

const serverDirectory = path.join(
  path.dirname(url.fileURLToPath(import.meta.url)),
  '${relServerPosix}'
);
process.chdir(serverDirectory);
await import(url.pathToFileURL(path.join(serverDirectory, 'src', 'index.js')));
`;
}

// Assembles a minimal production runtime at .lowdefy/docker from an already-built server directory.
// Instead of shipping the full node_modules (which includes the client-side block packages that are
// already compiled into dist/client), the runtime file closure of the Hono server is traced with
// @vercel/nft — the same mechanism the Vercel deployment uses. Run after `lowdefy build`.
async function dockerOutput({ context }) {
  const { directories, logger } = context;
  logger.info('Assembling Docker runtime output.');

  const serverDirectory = path.resolve(directories.server);
  const buildDirectory = path.resolve(directories.build);
  const clientDirectory = path.join(serverDirectory, 'dist', 'client');
  const outputDirectory = path.join(path.resolve(directories.config), '.lowdefy', 'docker');

  const entrypoints = [
    path.join(serverDirectory, 'src', 'index.js'),
    path.join(serverDirectory, 'src', 'app.js'),
  ];
  entrypoints.forEach((entrypoint) => {
    if (!fs.existsSync(entrypoint)) {
      throw new Error(`Cannot trace "${entrypoint}" — run "lowdefy build" first.`);
    }
  });
  if (!fs.existsSync(clientDirectory)) {
    throw new Error(`Cannot find built client at "${clientDirectory}" — run "lowdefy build" first.`);
  }

  // Paths are preserved relative to the trace base (the pnpm workspace root when the server
  // directory is a workspace member), so the server's relative node_modules symlinks still
  // resolve inside the output. The server lands at <relServer>/ inside the output directory.
  const base = findTraceBase({ serverDirectory });
  const relServer = path.relative(base, serverDirectory);
  const outputServerDirectory = path.join(outputDirectory, relServer);

  // Start clean so artifacts from a previous build do not leak into the image.
  await cleanDirectory(outputDirectory);

  // 1. The runtime file closure of the Hono server, traced with @vercel/nft — the app source, the
  //    build-generated plugin import files, and exactly the node_modules files they resolve to
  //    (through pnpm's symlinks, which are preserved).
  const fileCount = await copyTracedFiles({
    base,
    entrypoints,
    functionDirectory: outputDirectory,
    logger,
    processCwd: serverDirectory,
  });
  logger.info(`Traced ${fileCount} runtime files into the output.`);

  // 2. Artifacts the server reads from the filesystem at runtime (not imported, so not traced),
  //    plus src/ and lib/ wholesale as belt-and-braces alongside the traced copies. Unlike the
  //    Vercel output, dist/client ships in full — the Node server serves the static assets itself.
  await copyFileOrDirectory(
    path.join(serverDirectory, 'src'),
    path.join(outputServerDirectory, 'src')
  );
  await copyFileOrDirectory(
    path.join(serverDirectory, 'lib'),
    path.join(outputServerDirectory, 'lib')
  );
  await copyFileOrDirectory(buildDirectory, path.join(outputServerDirectory, 'build'));
  await copyFileOrDirectory(clientDirectory, path.join(outputServerDirectory, 'dist', 'client'));
  await copyFileOrDirectory(
    path.join(serverDirectory, 'package.json'),
    path.join(outputServerDirectory, 'package.json')
  );

  // 3. A uniform boot script so the container CMD is the same whether or not the server is nested
  //    under a workspace path inside the output.
  await writeFile(path.join(outputDirectory, 'start.mjs'), startScript({ relServer }));

  logger.info({ spin: 'succeed' }, 'Docker runtime output assembled at .lowdefy/docker.');
  await context.sendTelemetry();
}

export default dockerOutput;
