/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import fs from 'fs';
import path from 'path';
import getLowdefyVersion from '../utils/getLowdefyVersion.mjs';
import setupWatcher from '../utils/setupWatcher.mjs';

function lowdefyBuildWatcher(context) {
  const fixRelativePathConfigDir = (item) =>
    path.isAbsolute(item) ? item : path.resolve(context.directories.config, item);

  const callback = async (filePaths) => {
    const changedFiles = filePaths
      .flat()
      .map((filePath) => path.relative(context.directories.config, filePath));

    const lowdefyYamlModified = changedFiles.some(
      (filePath) => filePath === 'lowdefy.yaml' || filePath === 'lowdefy.yml'
    );
    if (lowdefyYamlModified) {
      const lowdefyVersion = await getLowdefyVersion(context);
      if (lowdefyVersion !== context.version && lowdefyVersion !== 'local') {
        context.shutdownServer();
        context.logger.warn('Lowdefy version changed. You should restart your development server.');
        process.exit();
      }
    }

    try {
      const isSkeletonChange =
        lowdefyYamlModified ||
        changedFiles.some((f) => !f.startsWith('pages/') && !f.startsWith('./'));

      if (isSkeletonChange) {
        await context.lowdefyBuild();
      } else {
        // Page-only changes: write signal file so the server invalidates its page cache
        const invalidatePath = path.join(context.directories.build, 'invalidatePages');
        fs.writeFileSync(invalidatePath, String(Date.now()));

        // Eagerly write raw page content so Tailwind can scan for new class candidates
        // before the JIT build runs. Tailwind's scanner extracts candidates from any text.
        const pageContents = changedFiles
          .filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'))
          .map((f) => {
            try {
              return fs.readFileSync(path.join(context.directories.config, f), 'utf8');
            } catch {
              return '';
            }
          })
          .join('\n');
        if (pageContents) {
          const sourcePath = path.join(context.directories.build, 'tailwind-page-sources.js');
          fs.writeFileSync(
            sourcePath,
            `// Generated by watcher — raw page content for Tailwind class scanning\nexport default ${JSON.stringify(pageContents)};\n`
          );
        }

        context.logger.info('Page files changed, invalidated all pages.');
      }
    } catch (error) {
      context.logger.error(error);
    } finally {
      await context.reloadClients();
    }
  };
  return setupWatcher({
    callback,
    context,
    ignorePaths: [
      '**/node_modules/**',
      ...context.options.watchIgnore.map(fixRelativePathConfigDir),
    ],
    watchPaths: [
      context.directories.config,
      ...context.options.watch.map(fixRelativePathConfigDir),
    ],
  });
}

export default lowdefyBuildWatcher;
