const authors = {
  gerrie: {
    id: 'gerrie',
    name: 'Gerrie van Wyk',
    title: 'Cofounder of Lowdefy',
    bio: 'Gerrie architects scalable software solutions and specializes in streamlining complex business processes. He cofounded Lowdefy to make building web apps accessible to everyone.',
    image: 'https://avatars.githubusercontent.com/u/7165064?v=4',
    github: 'https://github.com/Gervwyk',
    linkedin: 'https://www.linkedin.com/in/gervwyk/',
  },
  sam: {
    id: 'sam',
    name: 'Sam Tolmay',
    title: 'Cofounder of Lowdefy',
    bio: 'Sam leads the technical vision for Lowdefy, designing the config-first architecture that bridges the gap between no-code simplicity and full-code flexibility.',
    image: 'https://avatars.githubusercontent.com/u/23532753?v=4',
    github: 'https://github.com/SamTolmay',
    linkedin: 'https://www.linkedin.com/in/sam-tolmay-ba8566106/',
  },
  albert: {
    id: 'albert',
    name: 'Albert van Wyk',
    title: 'Cofounder of Lowdefy',
    bio: 'Albert drives product strategy at Lowdefy, ensuring the framework solves real problems for developers and teams building internal tools.',
    image: 'https://avatars.githubusercontent.com/u/25527299?v=4',
    github: 'https://github.com/ACvWyk',
    linkedin: 'https://www.linkedin.com/in/albert-van-wyk-43667919/',
  },
  salahuddin: {
    id: 'salahuddin',
    name: 'Salahuddin Saiet',
    title: 'Software Developer at Lowdefy',
    bio: 'Salahuddin is a software developer at Lowdefy, building and maintaining enterprise web applications using the Lowdefy framework.',
    image: 'https://avatars.githubusercontent.com/u/80051168?v=4',
    github: 'https://github.com/Saiby100',
    linkedin: 'https://www.linkedin.com/in/salahuddin-saiet-2a7190241/',
  },
  ioannis: {
    id: 'ioannis',
    name: 'Ioannis Ktistakis',
    title: 'Software Developer at Lowdefy',
    bio: 'Ioannis is a software developer at Lowdefy, building enterprise web applications and creating developer-focused content for the Lowdefy community.',
    image: 'https://avatars.githubusercontent.com/u/47716028?v=4',
    github: 'https://github.com/Yianni99',
    linkedin: 'https://www.linkedin.com/in/ioannis-ktistakis-38a750183/',
  },
  stephanie: {
    id: 'stephanie',
    name: 'Stephanie Smit',
    title: 'Software Developer at Lowdefy',
    bio: 'Stephanie is a software developer at Lowdefy, building enterprise web applications and contributing to the development of the Lowdefy framework.',
    image: 'https://avatars.githubusercontent.com/u/47713197?v=4',
    github: 'https://github.com/StephanieJKS',
    linkedin: 'https://za.linkedin.com/in/stephaniejksmit',
  },
  lowdefy: {
    id: 'lowdefy',
    name: 'Lowdefy',
    title: 'The Lowdefy Team',
    bio: 'Config-driven web framework built on Next.js. Build internal tools, dashboards, and CRUD apps with YAML configuration.',
    image: 'https://avatars.githubusercontent.com/u/47087496?v=4',
    github: 'https://github.com/lowdefy',
    linkedin: 'https://www.linkedin.com/company/lowdefy/',
  },
};

export default authors;
