/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import { type } from '@lowdefy/helpers';

/**
 * Turn the build's `blocksStatic` artifact into the `blockType → { toReport }`
 * registry walkBlocks consumes. The artifact is generated by build's
 * `writeBlockStaticImports` from the usage-counted block imports, filtered to
 * metas declaring `static: true`, and imported statically by `apiContext`, then
 * handed to the plugin as `app.blocksStatic`.
 *
 * An entry that does not expose a `toReport` function is dropped rather than
 * carried through — walkBlocks would skip it and warn, but dropping it here
 * keeps the malformed registry from masking a real "unsupported block" signal
 * with a "renderer present but broken" one.
 */
function resolveRenderer({ blocksStatic } = {}) {
  if (type.isNone(blocksStatic)) return {};
  const registry = {};
  Object.keys(blocksStatic).forEach((blockType) => {
    const renderer = blocksStatic[blockType];
    if (renderer && typeof renderer.toReport === 'function') {
      registry[blockType] = renderer;
    }
  });
  return registry;
}

export default resolveRenderer;
