/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import path from 'path';
import { writeFile } from '@lowdefy/node-utils';
import { mergeObjects } from '@lowdefy/helpers';

import readMobileBuildConfig from './readMobileBuildConfig.js';

// capacitor.config.json is a build artifact — config lives in lowdefy.yaml
// (mobile.appId, mobile.name, mobile.capacitor passthrough), one correct way.
async function generateCapacitorConfig({ context, devServerUrl }) {
  const mobileConfig = await readMobileBuildConfig({ context });
  if (!mobileConfig.appId) {
    throw new Error('"mobile.appId" is required in lowdefy.yaml to generate the Capacitor config.');
  }

  const generated = {
    '//': 'Generated by "lowdefy mobile build" from lowdefy.yaml mobile.* — do not edit.',
    appId: mobileConfig.appId,
    appName: mobileConfig.name ?? mobileConfig.appId,
    webDir: 'www',
    // androidScheme stays at the Capacitor default pending the device-matrix
    // cookie check (design open question 3).
    plugins: {
      // Native HTTP with a native cookie jar, patching fetch — no CORS
      // preflight against the server and Auth.js session cookies that
      // persist across app restarts (decision 14).
      CapacitorHttp: {
        enabled: true,
      },
    },
  };

  const config = mergeObjects([generated, mobileConfig.capacitor ?? {}]);

  if (devServerUrl) {
    // Dev-only: load the app from the LAN mobile Vite server for live reload.
    // Never baked into production builds (App Store posture, decision 15).
    config.server = { ...(config.server ?? {}), url: devServerUrl, cleartext: true };
  }

  const configPath = path.join(context.directories.mobileProject, 'capacitor.config.json');
  await writeFile(configPath, JSON.stringify(config, null, 2).concat('\n'));
  context.logger.info(`Generated capacitor.config.json for ${config.appId}.`);
  return config;
}

export default generateCapacitorConfig;
