/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import crypto from 'crypto';

const HEADER =
  /^# Generated by lowdefy journeys variants from (.+) \(([0-9a-f]{12})\)\. A rerun keeps this file once it is edited\.\n\n/;

function hashBody(body) {
  return crypto.createHash('sha1').update(body).digest('hex').slice(0, 12);
}

// The header line a variant file starts with: its source journey file and a
// hash of the generated text below it, so a rerun can tell a file someone
// edited (the hash no longer matches) from one left as generated.
function writeVariantHeader({ source, body }) {
  return `# Generated by lowdefy journeys variants from ${source} (${hashBody(
    body
  )}). A rerun keeps this file once it is edited.\n\n${body}`;
}

// Reads a variant file's header: { source, edited }, or null when the file
// has no generated header (written or rewritten by hand).
function readVariantHeader(text) {
  const match = HEADER.exec(text);
  if (match === null) {
    return null;
  }
  return { source: match[1], edited: hashBody(text.slice(match[0].length)) !== match[2] };
}

export { readVariantHeader };
export default writeVariantHeader;
