/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import fs from 'fs';
import path from 'path';
import YAML from 'yaml';
import { type } from '@lowdefy/helpers';

import buildVariantJourney from './buildVariantJourney.js';

function renderVariant({ journey, variant, source }) {
  const document = new YAML.Document(buildVariantJourney({ journey, variant }), {
    aliasDuplicateObjects: false,
  });
  document.commentBefore = ` Generated by lowdefy journeys variants from ${source}.`;
  const steps = document.get('steps');
  // One line per step, as journeys are written by hand: `- fill: { blockId: a, value: b }`.
  steps.items.forEach((step) => {
    step.items.forEach((pair) => {
      if (YAML.isCollection(pair.value)) {
        pair.value.flow = true;
      }
    });
  });
  Object.entries(variant.comments ?? {}).forEach(([index, comment]) => {
    steps.items[Number(index)].commentBefore = ` ${comment}`;
  });
  return document.toString({ lineWidth: 0 });
}

// Writes each variant to tests/journeys/_candidates/variants/
// <stem>-<kind>[-<n>].yaml, n counting variants of one kind when there are
// several. The same inputs give byte-identical files. Returns the paths.
function writeVariantFiles({ directories, filePath, journey, variants }) {
  const directory = path.join(directories.journeys, '_candidates', 'variants');
  const stem = path.basename(filePath, path.extname(filePath));
  const source = path.relative(directories.config, filePath);
  fs.mkdirSync(directory, { recursive: true });
  const counts = new Map();
  variants.forEach(({ kind }) => counts.set(kind, (counts.get(kind) ?? 0) + 1));
  const seen = new Map();
  return variants.map((variant) => {
    const n = (seen.get(variant.kind) ?? 0) + 1;
    seen.set(variant.kind, n);
    const suffix = counts.get(variant.kind) > 1 ? `-${n}` : '';
    const variantPath = path.join(directory, `${stem}-${variant.kind}${suffix}.yaml`);
    fs.writeFileSync(variantPath, renderVariant({ journey, variant, source }));
    return {
      path: variantPath,
      kind: variant.kind,
      placeholder: !type.isUndefined(variant.comments),
    };
  });
}

export default writeVariantFiles;
