/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

import fs from 'fs';
import os from 'os';
import path from 'path';

import generators from './generators/index.js';
import writeVariantFiles from './writeVariantFiles.js';

const journey = {
  name: 'member assigns an open ticket',
  pageId: 'tickets',
  user: 'none',
  steps: [
    { click: 'open_assign' },
    { fill: { blockId: 'assignee', value: 'Ada' } },
    { fill: { blockId: 'note', value: 'Urgent' } },
    { fill: { blockId: 'code', value: 'ABC' } },
    { click: 'assign_submit' },
    { wait: { request: 'assign_ticket' } },
    { expect: { text: { blockId: 'assign_success', contains: 'Assigned' } } },
  ],
};

const exercised = {
  pages: ['tickets'],
  appEvents: true,
  requests: [{ pageId: 'tickets', requestId: 'assign_ticket', calls: 1, write: true }],
  endpoints: [],
  events: [],
  rendered: {},
};

const pageConfigs = [
  {
    blockId: 'tickets',
    type: 'Box',
    slots: {
      content: {
        blocks: [
          { blockId: 'assignee', type: 'Selector', required: true },
          { blockId: 'note', type: 'TextArea' },
          {
            blockId: 'code',
            type: 'TextInput',
            validate: [
              { pass: { _regex: '^[A-Z]{3}$' }, status: 'error', message: 'Code is three letters' },
            ],
          },
        ],
      },
    },
  },
];

let directory;

beforeEach(() => {
  directory = fs.mkdtempSync(path.join(os.tmpdir(), 'lowdefy-variants-'));
});

afterEach(() => {
  fs.rmSync(directory, { recursive: true, force: true });
});

function writeAll() {
  const variants = ['negative', 'interrupt', 'double-submit'].flatMap((kind) =>
    generators[kind].flatMap((generator) =>
      generator({ journey, exercised, pageConfigs, i18n: {} })
    )
  );
  const directories = { config: directory, journeys: path.join(directory, 'tests', 'journeys') };
  return writeVariantFiles({
    directories,
    filePath: path.join(directories.journeys, 'assign.yaml'),
    journey,
    variants,
  }).map((file) => ({ ...file, content: fs.readFileSync(file.path, 'utf8') }));
}

const HEADER = '# Generated by lowdefy journeys variants from tests/journeys/assign.yaml.\n\n';

test('writeVariantFiles writes each kind byte for byte, numbering several of one kind', () => {
  const written = writeAll();
  const variantsDirectory = path.join('tests', 'journeys', '_candidates', 'variants');
  expect(written.map((file) => path.relative(directory, file.path))).toEqual([
    path.join(variantsDirectory, 'assign-negative-1.yaml'),
    path.join(variantsDirectory, 'assign-negative-2.yaml'),
    path.join(variantsDirectory, 'assign-interrupt.yaml'),
    path.join(variantsDirectory, 'assign-double-submit.yaml'),
  ]);
  expect(written.map(({ kind, placeholder }) => [kind, placeholder])).toEqual([
    ['negative', false],
    ['negative', true],
    ['interrupt', false],
    ['double-submit', false],
  ]);
  expect(written[0].content)
    .toBe(`${HEADER}name: "member assigns an open ticket — negative: assignee left empty"
pageId: tickets
user: none
variant:
  of: member assigns an open ticket
  kind: negative
  detail: assignee left empty
steps:
  - click: open_assign
  - fill: { blockId: assignee, value: "" }
  - fill: { blockId: note, value: Urgent }
  - fill: { blockId: code, value: ABC }
  - click: assign_submit
  - expect: { text: { blockId: assignee, contains: This field is required } }
  - expect: { calls: { request: assign_ticket, pageId: tickets, count: 0 } }
`);
  expect(written[1].content)
    .toBe(`${HEADER}name: 'member assigns an open ticket — negative: code breaks "Code is three letters"'
pageId: tickets
user: none
variant:
  of: member assigns an open ticket
  kind: negative
  detail: code breaks "Code is three letters"
steps:
  - click: open_assign
  - fill: { blockId: assignee, value: Ada }
  - fill: { blockId: note, value: Urgent }
  # Type a value that fails the rule: Code is three letters
  - fill: { blockId: code, value: null, from: shape }
  - click: assign_submit
  - expect: { text: { blockId: code, contains: Code is three letters } }
  - expect: { calls: { request: assign_ticket, pageId: tickets, count: 0 } }
`);
  expect(written[2].content)
    .toBe(`${HEADER}name: 'member assigns an open ticket — interrupt: reload before "assign_submit"'
pageId: tickets
user: none
variant:
  of: member assigns an open ticket
  kind: interrupt
  detail: reload before "assign_submit"
steps:
  - click: open_assign
  - fill: { blockId: assignee, value: Ada }
  - fill: { blockId: note, value: Urgent }
  - fill: { blockId: code, value: ABC }
  - goto: tickets
  - click: open_assign
  - fill: { blockId: assignee, value: Ada }
  - fill: { blockId: note, value: Urgent }
  - fill: { blockId: code, value: ABC }
  - click: assign_submit
  - wait: { request: assign_ticket }
  - expect: { text: { blockId: assign_success, contains: Assigned } }
  - expect: { calls: { request: assign_ticket, pageId: tickets, count: 1 } }
`);
  expect(written[3].content)
    .toBe(`${HEADER}name: 'member assigns an open ticket — double-submit: double click "assign_submit"'
pageId: tickets
user: none
variant:
  of: member assigns an open ticket
  kind: double-submit
  detail: double click "assign_submit"
steps:
  - click: open_assign
  - fill: { blockId: assignee, value: Ada }
  - fill: { blockId: note, value: Urgent }
  - fill: { blockId: code, value: ABC }
  - click: { blockId: assign_submit, count: 2 }
  - wait: { request: assign_ticket }
  - expect: { text: { blockId: assign_success, contains: Assigned } }
  - expect: { calls: { request: assign_ticket, pageId: tickets, count: 1 } }
`);
});

test('writeVariantFiles writes the same bytes on a second run', () => {
  const first = writeAll().map(({ content }) => content);
  expect(writeAll().map(({ content }) => content)).toEqual(first);
});
