/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// The PostToolUse hook body agent-setup writes to .claude/hooks/. It is
// committed and runs on every teammate's machine, so it must be silent and
// exit 0 whenever no dev server is answering: it reads the dev manager's lock
// for the port and asks the running server what it already knows, rather than
// running a build of its own. `lowdefy check` is a full production build and
// belongs in the pre-commit hook, not here.
//
// The generated script uses string concatenation rather than template
// literals so this template stays readable.
function postEditHookScript({ appPath }) {
  return `#!/usr/bin/env node
/*
  Generated by 'lowdefy agent-setup'.

  Claude Code PostToolUse hook: after an edit inside the Lowdefy config
  directory, report what the running dev server saw - build errors and
  warnings from the rebuild the edit triggered, plus the newest browser and
  server errors. Exits 0 in silence when no dev server is running, so it is
  harmless for anyone who has not started one.

  Delete this file and the 'PostToolUse' entry in .claude/settings.json to
  turn it off.
*/
import fs from 'fs';
import path from 'path';

const APP_PATH = ${JSON.stringify(appPath)};
// The rebuild is debounced, so the status of the edit that just happened is
// not there yet. Poll for a build newer than the edit, then give up and
// report what is there with a note.
const SETTLE_MS = 5000;
const POLL_MS = 250;
const REQUEST_TIMEOUT_MS = 2000;
const MAX_LISTED = 5;

const projectDirectory = process.env.CLAUDE_PROJECT_DIR ?? process.cwd();
const configDirectory = path.resolve(projectDirectory, APP_PATH);

function readStdin() {
  return new Promise((resolve) => {
    if (process.stdin.isTTY) {
      resolve('');
      return;
    }
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (chunk) => {
      data += chunk;
    });
    process.stdin.on('end', () => resolve(data));
    process.stdin.on('error', () => resolve(''));
  });
}

function editedFilePath(input) {
  const toolInput = input && input.tool_input;
  const filePath = toolInput && toolInput.file_path;
  if (typeof filePath !== 'string' || filePath === '') return null;
  return path.resolve(projectDirectory, filePath);
}

// Build artifacts and installed packages are not config - an edit there says
// nothing about the app's build.
function isConfigFile(filePath) {
  const relative = path.relative(configDirectory, filePath);
  if (relative === '' || relative.startsWith('..') || path.isAbsolute(relative)) return false;
  const segments = relative.split(path.sep);
  return !segments.includes('.lowdefy') && !segments.includes('node_modules');
}

// The dev manager advertises the port it settled on in its lock file.
function devServerPort() {
  try {
    const lockPath = path.join(configDirectory, '.lowdefy', 'dev', '.manager.lock');
    const lock = JSON.parse(fs.readFileSync(lockPath, 'utf8'));
    return Number.isInteger(lock.port) ? lock.port : null;
  } catch {
    return null;
  }
}

async function fetchBuildStatus(port) {
  try {
    const response = await fetch('http://localhost:' + port + '/lowdefy-docs/build-status', {
      signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
    });
    if (!response.ok) return null;
    return await response.json();
  } catch {
    return null;
  }
}

function buildTime(status) {
  const timestamp = status && status.build && status.build.timestamp;
  const time = Date.parse(timestamp ?? '');
  return Number.isNaN(time) ? 0 : time;
}

async function buildStatusAfter(port, editedAt) {
  const deadline = Date.now() + SETTLE_MS;
  let status = await fetchBuildStatus(port);
  if (status === null) return null;
  while (buildTime(status) < editedAt && Date.now() < deadline) {
    await new Promise((resolve) => setTimeout(resolve, POLL_MS));
    const next = await fetchBuildStatus(port);
    if (next === null) return status;
    status = next;
  }
  return status;
}

function describe(entry) {
  const message = entry.message ?? entry.name ?? JSON.stringify(entry);
  const source = entry.source ? ' [' + entry.source + ']' : '';
  const name = entry.name && entry.message ? entry.name + ': ' : '';
  return '  - ' + name + message + source;
}

function section(title, entries) {
  if (!Array.isArray(entries) || entries.length === 0) return [];
  const listed = entries.slice(-MAX_LISTED).reverse();
  const more = entries.length > listed.length ? [' ... and ' + (entries.length - listed.length) + ' more'] : [];
  return [title].concat(listed.map(describe), more);
}

function report({ status, port, settled }) {
  const build = status.build ?? {};
  const errors = build.errors ?? [];
  const warnings = build.warnings ?? [];
  const serverErrors = status.serverErrors ?? [];
  const clientErrors = status.clientErrors ?? [];
  if (
    errors.length === 0 &&
    warnings.length === 0 &&
    serverErrors.length === 0 &&
    clientErrors.length === 0
  ) {
    return null;
  }
  const lines = ['Lowdefy dev server (port ' + port + ') build status: ' + (build.status ?? 'unknown')];
  if (!settled) {
    lines.push('(the rebuild for this edit may not have finished - this is the previous build)');
  }
  return lines
    .concat(
      section('build errors:', errors),
      section('build warnings:', warnings),
      section('server errors (newest first):', serverErrors),
      section('browser errors (newest first):', clientErrors)
    )
    .join('\\n');
}

async function main() {
  const editedAt = Date.now();
  const raw = await readStdin();
  let input;
  try {
    input = JSON.parse(raw);
  } catch {
    return;
  }
  const filePath = editedFilePath(input);
  if (filePath === null || !isConfigFile(filePath)) return;

  const port = devServerPort();
  if (port === null) return;

  const status = await buildStatusAfter(port, editedAt);
  if (status === null) return;

  const text = report({ status, port, settled: buildTime(status) >= editedAt });
  if (text === null) return;

  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PostToolUse',
        additionalContext: text,
      },
    })
  );
}

main();
`;
}

export default postEditHookScript;
