/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// The body of the pre-commit hook agent-setup writes under --git-hooks. This
// is where `lowdefy check` belongs: a full production build once per commit is
// cheap, on every file edit it is not. Journeys are narrowed to the pages the
// staged files touch through the page -> journeys index `lowdefy test
// --coverage` writes; without that index the hook says so and runs them all.
//
// The generated script uses string concatenation rather than template literals
// so this template stays readable.
function preCommitHookScript({ appPath, lowdefyCommand }) {
  return `#!/usr/bin/env node
/*
  Generated by 'lowdefy agent-setup --git-hooks'.

  Runs 'lowdefy check' on the staged Lowdefy config, then the journeys that
  cover the pages those files touch. Commits nothing itself; a non-zero exit
  fails the commit. Delete this file and its caller to turn it off.
*/
import fs from 'fs';
import path from 'path';
import { spawnSync } from 'child_process';

const APP_PATH = ${JSON.stringify(appPath)};
const LOWDEFY_COMMAND = ${JSON.stringify(lowdefyCommand)};

const projectDirectory = process.cwd();
const configDirectory = path.resolve(projectDirectory, APP_PATH);

function run(args) {
  const result = spawnSync(LOWDEFY_COMMAND + ' ' + args.join(' '), {
    cwd: configDirectory,
    shell: true,
    stdio: 'inherit',
  });
  return result.status === 0;
}

function stagedConfigFiles() {
  const result = spawnSync('git', ['diff', '--cached', '--name-only', '--diff-filter=ACM'], {
    cwd: projectDirectory,
    encoding: 'utf8',
  });
  if (result.status !== 0) return [];
  return result.stdout
    .split('\\n')
    .filter((line) => line !== '')
    .map((line) => path.resolve(projectDirectory, line))
    .filter((filePath) => {
      const relative = path.relative(configDirectory, filePath);
      if (relative === '' || relative.startsWith('..') || path.isAbsolute(relative)) return false;
      return !relative.split(path.sep).includes('.lowdefy');
    });
}

// Written by 'lowdefy test --coverage' as { pages: { <pageId>: [journeyName] } }.
function readJourneyIndex() {
  try {
    const indexPath = path.join(configDirectory, '.lowdefy', 'test', 'journeyIndex.json');
    const index = JSON.parse(fs.readFileSync(indexPath, 'utf8'));
    return index && typeof index.pages === 'object' ? index.pages : null;
  } catch {
    return null;
  }
}

// A page's config lives in a file or directory named for its id - the only
// join available without building the app in the hook.
function touchesPage(files, pageId) {
  return files.some((filePath) => {
    const relative = path.relative(configDirectory, filePath);
    const segments = relative.split(path.sep);
    return (
      segments.includes(pageId) || segments.includes(pageId + '.yaml') || segments.includes(pageId + '.yml')
    );
  });
}

function journeysForFiles(files) {
  const pages = readJourneyIndex();
  if (pages === null) return null;
  const journeys = new Set();
  for (const pageId of Object.keys(pages)) {
    if (touchesPage(files, pageId)) {
      for (const name of pages[pageId] ?? []) journeys.add(name);
    }
  }
  return [...journeys];
}

function main() {
  const files = stagedConfigFiles();
  if (files.length === 0) return 0;

  console.error('lowdefy check (' + files.length + ' staged config file(s))');
  if (!run(['check', '--json'])) {
    console.error('lowdefy check failed - commit aborted.');
    return 1;
  }

  // 'lowdefy test' finds a running dev server itself and drives it rather than
  // booting a second one, so the hook does not pass a url.
  const journeys = journeysForFiles(files);

  if (journeys === null) {
    console.error(
      'No ' +
        path.join('.lowdefy', 'test', 'journeyIndex.json') +
        ' - running all journeys. Run "lowdefy test --coverage" to write it.'
    );
    return run(['test']) ? 0 : 1;
  }
  if (journeys.length === 0) {
    console.error('No journeys cover the staged pages - skipping journeys.');
    return 0;
  }
  console.error('Running ' + journeys.length + ' journey(s) for the staged pages.');
  for (const name of journeys) {
    if (!run(['test', '--filter', JSON.stringify(name)])) {
      console.error('Journey "' + name + '" failed - commit aborted.');
      return 1;
    }
  }
  return 0;
}

process.exit(main());
`;
}

export default preCommitHookScript;
