/*
  Copyright 2020-2026 Lowdefy, Inc

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Generates the source of the Claude Code Stop hook script installed by
// `lowdefy agent-setup`. The script itself has no dependencies (not even
// Lowdefy packages) since Claude Code runs it standalone with `node`, outside
// any project install step.
function stopHookScript({ port }) {
  return `#!/usr/bin/env node
/*
 * Lowdefy Feedback Mode - Claude Code Stop hook.
 *
 * Generated by \`lowdefy agent-setup\` - safe to delete if you don't want
 * browser feedback (Cmd/Ctrl+/ in the running app) to wake idle sessions.
 *
 * When a Claude Code session goes idle, this script asks the local Lowdefy
 * dev server for any pending feedback annotations. If there are any, it
 * blocks the stop and injects them as the reason, so the session continues
 * with the feedback in context. If the dev server is not running, or
 * anything goes wrong, it fails open and lets the session stop normally.
 */

async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks).toString('utf8');
}

async function main() {
  const raw = await readStdin();

  let input;
  try {
    input = JSON.parse(raw);
  } catch {
    // Unparseable input - fail open.
    process.exit(0);
  }

  if (input.stop_hook_active) {
    // Loop protection: this hook already blocked this cycle.
    process.exit(0);
  }

  let response;
  try {
    response = await fetch(
      'http://localhost:${port}/lowdefy-feedback/pending?consume=1',
      { signal: AbortSignal.timeout(1500) }
    );
  } catch {
    // Dev server unreachable - fail open, never block the session on this.
    process.exit(0);
  }

  if (!response.ok) {
    process.exit(0);
  }

  let body;
  try {
    body = await response.json();
  } catch {
    process.exit(0);
  }

  if (!body || !body.count) {
    process.exit(0);
  }

  process.stdout.write(JSON.stringify({ decision: 'block', reason: body.formatted }));
  process.exit(0);
}

main();
`;
}

export default stopHookScript;
